[project]
name = "buildserver"
requires-python = ">=3.8"
version = "0.1.0"

dependencies = [
    "flask~=2.2.2",
]

[project.optional-dependencies]
dev = [
    "black~=24.3.0",
    "pip-tools",
    "pytest~=7.2.0",
]
