name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          make install
          pip install pip-tools
      - name: Run linter
        run: make lint
      - name: Run tests
        run: make tests
      - name: Update requirements
        run: make requirements
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: energyhub:latest
